### ISSUE TITLE
Clean up lib/cosi_test.go

### ISSUE THREAD

**Issue by ineiti** [dedis/cosi#6]
Decide what to do with the dead code. Perhaps move it into a subdirectory and exclude it from `go test`?

**Comment by nikkolasg** [comment]
what is the dead code ? commented code ?

**Comment by liamsi** [comment]
I would say commented code and functions which aren't called/used.

**Comment by ineiti** [comment]
From Ismail, I think it's a good option:

Also it would be good if the repo was self-contained. I think 
/_own "github.com/nikkolasg/learning/crypto/util”_/
should be moved into the cosi or cothority repo, too.

And using `dbg.Lvl1` instead of `println` would make it compatible with using `go test -v`...

**Comment by liamsi** [comment]
The commented code should be removed or at least commented consistently (and not a mixture of block and line comments). If we keep the code it might be useful if we kept it as self-contained as possible (move the `own` package to cosi/cothority maybe?)
currently it looks like this

```
    // XXX In order to check the compatibility with the bford fork of
    // golang-x-crypto we do a comparison in the test. Uncomment if you want to
    // try.
    /*"github.com/bford/golang-x-crypto/ed25519"*/ //"github.com/bford/golang-x-crypto/ed25519/cosi"
    /*own "github.com/nikkolasg/learning/crypto/util"*/
```

**Comment by nikkolasg** [comment]
For the self-contained thing, we already need to import from the repo of bryan anyway; but sure, we can do that.
Debug level thing definitely!

**Comment by nikkolasg** [comment]
I dont what to do regarding making the thing self contained because the _own_ contains very .. un-proper code, I also directly copied some primitives from agl code to make it work...  At the same time, it enables us to quickly look whether both implementation are compatible. Should I copy everything no matter how it looks ?

**Comment by ineiti** [comment]
is it possible to give it it's own test-function, perhaps in another directory, that is only tested when needed to compare?

What is 'agl'-code?

**Comment by nikkolasg** [comment]
? Why not testing every time if we want that compatibility ? But does it change anything if we want to test it once or many as long as we include it ?

AGL code is basically the one in golang-x-crypto in the internal package of https://github.com/golang/crypto/tree/master/ed25519

**Comment by ineiti** [comment]
IIRC we had an import-problem, no?

**Comment by nikkolasg** [comment]
Well, the _problem_ is that the test uses some code that i have in my own repo, because i did not want to pollute  cosi at the time. And to really test things, I needed some primitives so I just copied in my repo. Now I think I'll just copy again in the tests functions, because even if it is a bit ugly to copy things here, it's still a necessary test to get compatible behavior ...
